### ISSUE TITLE
Empty TODOs

### ISSUE THREAD

**Issue by VladimirMarkelov** [lavifb/todo_r#8]
Is it possible to include TODOs that have empty text?

I have two TODOs (in different places of the same file):

```
// TODO: get list of args
...
// TODO:
```
When running `todor` I see only one:
```
PS > todor -V
Todo_r 0.7.2
PS > todor
filelist\src\lst.rs
  line 964    TODO   get list of args
```

**Comment by lavifb** [comment]
Taking a look at the regex, `// TODO: ` with a space at the end will probably get caught but without a space it wont get recognized.

When I have time ill take a look and see if we can modify the regex to include it without the space

**Comment by lavifb** [comment]
I wrote up a quick solution. I'm gonna take a second look at this PR when I have a bit more time

**Comment by VladimirMarkelov** [comment]
Thank you a lot!

**Comment by lavifb** [comment]
Sorry for the delay, I think the PR looks fine but the build is now failing on Windows and I have not had the time to look into why that is (I'm guessing there's a dependency I updated that broke windows support...). In the meantime, feel free to build that branch and maybe use this as a chance to test it out a little and make sure it works in your use case

**Comment by VladimirMarkelov** [comment]
No problem. I can wait.

As I see in logs, it downloads `gnu` but fails on msvc build. It looks suspicious, though I have never tried to build with msvc on Windows - I use mingw/gnu:

In the beginning I see a line `$ export TARGET=x86_64-pc-windows-msvc`, but a few lines later `info: syncing channel updates for 'beta-x86_64-pc-windows-gnu'`

And finally it fails with:

```
error[E0463]: can't find crate for `core`
  |
  = note: the `x86_64-pc-windows-msvc` target may not be installed
```

**Comment by lavifb** [comment]
Yeah as far as I can tell travis has changed their windows toolchain to use gnu instead of msvc. This is particularly annoying because I originally set it up as msvc because thats what travis supported >_>

**Comment by lavifb** [comment]
Im going to change to use windows-gnu. Itll be easier to maintain that build anyway

**Comment by lavifb** [comment]
At some point im going to switch completely to github actions...

**Comment by lavifb** [comment]
Released new version with this feature https://github.com/lavifb/todo_r/releases/tag/v0.7.3

**Comment by VladimirMarkelov** [comment]
I tried and it seems working. Thank you a lot!
